version: '3'
services:
  db:
    image: postgres:10.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: adventureworks
    volumes:
      - ./datadb:/tmp
  mq:
    image: rabbitmq:3.7.5-management
    hostname: app-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./datamq/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
  reviewer: 
    build: ./workers/reviewProcessor
    depends_on:
      - mq
  dbworker: 
    build: ./workers/dbProcessor
    depends_on:
      - db
      - mq
  notifier: 
    build: ./workers/notificationProcessor
    depends_on:
      - mq     
  app:
    build: .
    ports:
      - "8888:8888"
    depends_on: 
      - db
      - mq